server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messengerdb
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: message-group
    auto-offset-reset: earliest
    topic:
      name: message-topic
      partitions: 10
      replicas: 1